# Generated by Django 4.1.3 on 2022-11-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
