# Generated by Django 4.1.3 on 2022-12-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSlider',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='OurClientReview',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='heading', max_length=30)),
                ('Message', models.CharField(max_length=2000)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
